version: '3'

services:
  webserver:
    build:
      context: ./webserver
    container_name: 'webserver'
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.31.97"
      PHP_IDE_CONFIG: "serverName=docker.local"
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCUMENT_ROOT-../lollyai/merlin/httpdocs}:/var/www/merlin
      - ${DOCUMENT_ROOT-../raw_mvc/raw.mvc/httpdocs}:/var/www/raw
      - ${PHP_INI-./config/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
